### ISSUE TITLE
Problém s drag-n-drop importem ZIPu 

### ISSUE THREAD

**Issue by pavelkovar** [tfedor/datamodeler#10]
Ahoj, nedaří se mi nahrát do kreslítka ZIP [sqldev-sources.zip](https://github.com/tfedor/datamodeler/files/1102914/sqldev-sources.zip). Po importu se zobrazí následující chyba:

![screenshot_20170626_191952](https://user-images.githubusercontent.com/19745438/27551628-7938d13a-5aa4-11e7-828c-08432eaaf1fc.png)

**Comment by tfedor** [comment]
Fixnute
