### ISSUE TITLE
Událost po načtení modelu ze souboru - funkce loadBlob

### ISSUE THREAD

**Issue by pavelkovar** [tfedor/datamodeler#11]
Ahoj, bylo by možné poupravit funkci _DBSDM.File.loadBlob_ tak, aby vracela _Promise_ (nebo umožnila nastavit callback), skrze kterou by šlo odchytit načtení celého modelu do kreslítka? 

Například:
``` javascript
var file = document.getElementById("file").files[0];
DBSDM.File.loadBlob(canvas, file)
    .then(function() {
        var exportedJSON = canvas.export(false, false);
        // ...
    });
```

Nyní to řešíme nastavením drobné časové prodlevy před voláním exportu.

**Comment by tfedor** [comment]
Nebude to problem ale dostanem sa k tomu najskor az dalsi vikend pravdepodobne.

**Comment by pavelkovar** [comment]
Díky, nijak na to nespěcháme, stačí až budeš mít volnou chvíli.

**Comment by tfedor** [comment]
Hotovo

**Comment by pavelkovar** [comment]
Díky!
