### ISSUE TITLE
Jak komponentě říci, že jsou data uložena

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#13]
Narazili jsme na problém, že nevíme jak máme komponentě říci, že data byla uložena AJAXem a že odchod ze stránky je tedy možný bez upozorňování.
Z kódu jsme vykoukali, že bychom mohli použít import, což ale není v souladu s úkolem #12.

Promysli prosím, zda by nešlo přidat něco jako flagu `isSaved` kterou by bylo možné zvenku nastavit na true, a následně by se interně změnila na false při jakékoliv akci provedené v kreslítku.

**Comment by tfedor** [comment]
Jednak je mozne pri exporte nastavit `saveRef` na `true`, pripadne je mozne zavolat `updateDataReference()` na Canvase
