### ISSUE TITLE
Identifikační závislost se ze ZIPu importuje naopak!

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#16]
U identifikační závislosti otáčí místo kde je čárka (identifikační závislost nakreslená)

Je to vidět po načtení do kreslítka u vazby LOD - Clen posádky.

Toto je velký problém.

[sql-design.zip](https://github.com/tfedor/datamodeler/files/1464464/sql-design.zip)

**Comment by tfedor** [comment]
Malo by byt fixnute

**Comment by oldamalec** [comment]
Je to fixnuté jen u mnohonásobných vazeb, když je identifikační vazba 1:1, tak se to stále importuje naopak.

Toto prosím opravit urgentně.

Dodávám ZIP, kde je to vidět
(např **účast** - **skupina** je už správně, ale **zápas** - **výsledek** spolu s dalšími mnohonásobnými vazbami je špatně.

[truneja1-sqldevsource.zip](https://github.com/tfedor/datamodeler/files/1471587/truneja1-sqldevsource.zip)
