### ISSUE TITLE
Porovnávání modelů v correct modu

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#3]
šlo by do kreslítka při correct modu strčit rovnou dva jsony - studentova odpověď a referenční odpověď a kreslítko by zobrazovalo rozdíly formou obarvení? A učitel by podle toho mohl označit věci které opravdu chce označit jako špatné...

**Comment by tfedor** [comment]
Ako sa to ma spravat ked chybaju alebo prebyvaju entity/vztahy?

**Comment by oldamalec** [comment]
Jelikož se to bude porovnávat s referencí, která má být zaručeně správně, tak přebývající asi označit stejně jako chybné. Chybějící asi označit nepůjdou...

~~Taky prosím mysli na to, že **označení chyb kreslítkem** má být pouze *doporučení* pro učitele, který poté opravdové **označení chyb** musí stejně provést manuálně - jde mi o to aby to z UI bylo jasné a učitel si třeba nemyslel, že už to je takhle označené...~~

**Comment by oldamalec** [comment]
Omluvám se, beru zpět, chyba porozumění požadavku.

Kreslítko to bude označovat **tak, jak to označuje i učitel**. Tomu tedy případně bude stačit uložit
