### ISSUE TITLE
Problém s ISA v Chrome

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#5]
Jirka Hunka:
> jo a kouslo se pěkně kreslítko jednomu studentovi...
> nějak se mu vše naházelo na levou stranu nahoru a nedalo se s tim nic dělat

> A bohuzel neni jediny - jakmile daji do modelu ISA, tak to v urcitem procentu pripadu zlobi. Co mi kdo hlasil problem s modelem, vzdycky tam mel ISA.

> A ted se mi i podarilo vysledovat souvislost - ve Firefoxu to funguje, v Chrome to zlobi. Staci udelat ISA, ulozit do ni 2 entity a dat ulozit diagram. Razem ti to zduplikuje vnorene entity a dela to bordel. Takze Chrome a ISA nejsou kompatibilni. Minimalne Chrome co je v ucebnach.

Přikládám JSON postiženého studenta

[json.zip](https://github.com/tfedor/datamodeler/files/957786/json.zip)

**Comment by tfedor** [comment]
Mno, problem je v tom JSONe, ale netusim jak ho nasimulovat. V jsone je jedna entita viackrat s roznymi parentami.

Vyrobil som model s 3 entitami, 2 z nich boli v ISA tej prvej, ulozil a importoval bez problemov. Skusal som a v Chrome

**Comment by oldamalec** [comment]
Takže už v pořádku?

**Comment by tfedor** [comment]
Ano, malo by to byt fixnute, ale tie stare jsony kde to nefungovalo nebudu fungovat. Nove modely uz budu spravne (neodstranovala sa tam jedna referencia)

**Comment by oldamalec** [comment]
Jasně, díky
