### ISSUE TITLE
Problém s načtením modelu

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#6]
Ahoj Tomáši, prosím zkus si importovat tento model...
[diplomka-behalkar-dmd.zip](https://github.com/tfedor/datamodeler/files/973199/diplomka-behalkar-dmd.zip)

**Comment by tfedor** [comment]
Wow. Kym zistim ci to je, mozete si to exportovat ako data a znovu importovat, nerozlozi sa to najlepsie ale bude sa s tym dat pracovat.

V tom zipe je JSON:
[data.zip](https://github.com/tfedor/datamodeler/files/973210/data.zip)

**Comment by oldamalec** [comment]
Díky za tip

Jirka:
> když se to uloží, a zase otevře tak se to srovná..

**Comment by tfedor** [comment]
Znova som na to pozrel a myslim ze to je proste blbo ulozene z SQL developeru. Ked si ten subor otvorim v SQLDev tak vyzera tiez divne, tak neviem...

**Comment by oldamalec** [comment]
ok zatím to uzavřeme
