### ISSUE TITLE
Nahrání modelu tlačítkem (ne drag-n-drop)

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#7]
Od veřejnosti vznikl požadavek na nahrávání modelu tlačítkem, nikoliv drag-n-drop
https://gitlab.fit.cvut.cz/malecold/newDBS-bug/issues/272

Myslíš že by to bylo možné někam zahrnout, nebo podnět zamítneme?

**Comment by oldamalec** [comment]
Toto má nižší prioritu

**Comment by tfedor** [comment]
Pridana podpora, zapne sa zavolanim `canvas.attachFileUploadInput("selector");` na canvase, pricom selector je CSS selektor na input.

Priklad:
```
    <input type="file" id="fileUpload">

    <script>
        ...
        var canvas = new DBSDM.Canvas();
        canvas.create(parent);
        canvas.attachFileUploadInput("#fileUpload");
    </script>
```
