### ISSUE TITLE
Opět problém s ISA

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#8]
Ahoj, včera při zkoušce se kreslítko zaseklo těm studentům, kteří se pokusili namodelovat ISA vztah.

Přikládám soubory, co se uložilo do DB a amatérské fotky pořízené na zkoušce, v jakém stavu zůstalo kreslítko zaseklé.

[ISA_fail.zip](https://github.com/tfedor/datamodeler/files/1044142/ISA_fail.zip)

**Comment by oldamalec** [comment]
Šlo by úkoly zvýšit prioritu?

**Comment by tfedor** [comment]
aky mal byt vysledok? Na obrazkoch nic s ISA nevidno

**Comment by tfedor** [comment]
Nabuduce ked sa nejak kreslitko zasekne namiesto obrazkov by bolo lepsie prilozit log z javascript console

**Comment by oldamalec** [comment]
No právě, ve chvíli, kdy studenti začali modelovat ISU, se to zaseklo.
Já u toho nebyl, tohle je vše co mi bylo předáno, informuji pověřené osoby o vhodnosti logu z konzole.

**Comment by tfedor** [comment]
Alebo aspon postup akym vytvarali ISA potrebujem, ked to skusam normalne tak ISA funguje, nejak to zreprodukovat.

**Comment by oldamalec** [comment]
Nešlo by něco zjistit z těch jsonů? tam náznak isy je

**Comment by tfedor** [comment]
Problem bol ASI v tom, ze ked bola vytvorena hierarchia _B is A_, a uzivatel sa snazil zmenit na _A is B_, v jednom kroku, tak to zamrzlo, pretoze sa to snazilo manipulovat s DOMom tak, jak sa neda. Zakazal som to, teraz sa nic nestane pri takomto pokuse, pretoze pri zlozitejsich hierarchiach typu _C is B is A_ nie je jasne ci pri kliknuty na A a tvorbe ISA na C chce aby vysledna hierarchia bola _A is C is B_ alebo _B is A is C_. V reale asi taketo hierarchie nebudu, ale kreslitko ich podporuje cize...

Ked to chce zmenit, msui najprv hierarchiu rozdeit (kliknut na plochu pri tvorbe isa) a potom to vytvorit spravne.

**Comment by oldamalec** [comment]
Jasně, hned to nasadím do portálu, myslím že by to mohlo pomoci. Díky!
