### ISSUE TITLE
Smazání entity z ISA a vytvoření stejné entity znovu vede na její dvojí uložení

### ISSUE THREAD

**Issue by oldamalec** [tfedor/datamodeler#9]
Kroky k replikaci:

* vytvoř entitu A
* vytvoř entitu B
* nastav A jako is a... B, tedy B je nadtyp
* smaž A
* vytvoř novou entitu A
* ulož

Ve výsledku jsou uloženy dvě entity A, chybně i ta, která je v relaci s B

**Comment by tfedor** [comment]
Fixed

**Comment by oldamalec** [comment]
díky, nasazeno
